language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '12'
  - '10'
  - '8'
os:
  - osx
  - linux
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: deploy
      name: "npm release"
      script: npm run semantic-release
      if: branch = master
